version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@mapbox/mapbox-sdk"
    versions:
    - 0.11.0
    - 0.12.0
